# Builds data/analogues.json: global reference companies, and the Indian firms
# on the Indi-Space page that do comparable work.
import json, io

REPO = r'D:\11 Bangalore 2026\1 Takshashila Institution\Argos Collab\sat-orbit-map'

# id: (name, country, cat, focus, url)
G = {
 'iceye':        ('ICEYE', 'Finland', 'eo', 'X-band SAR smallsat constellation; all-weather, day-night imaging and flood intelligence', 'https://www.iceye.com/'),
 'capella':      ('Capella Space', 'USA', 'eo', 'Commercial X-band SAR with sub-metre spotlight imaging', 'https://www.capellaspace.com/'),
 'synspective':  ('Synspective', 'Japan', 'eo', 'StriX small SAR satellites and ground-deformation analytics', 'https://synspective.com/'),
 'umbra':        ('Umbra', 'USA', 'eo', 'Very-high-resolution commercial SAR, sold as open data licences', 'https://umbra.space/'),
 'iqps':         ('iQPS', 'Japan', 'eo', 'QPS-SAR constellation built around a deployable lightweight antenna', 'https://i-qps.net/en/'),
 'planet':       ('Planet Labs', 'USA', 'eo', 'Daily global optical imaging (Dove, SkySat, Pelican) plus an analytics platform', 'https://www.planet.com/'),
 'maxar':        ('Vantor (ex-Maxar Intelligence)', 'USA', 'eo', 'Sub-30 cm optical imaging and the WorldView/Legion constellations', 'https://www.maxar.com/'),
 'satellogic':   ('Satellogic', 'Argentina / USA', 'eo', 'Vertically integrated sub-metre optical and hyperspectral imaging at low cost', 'https://satellogic.com/'),
 'blacksky':     ('BlackSky', 'USA', 'eo', 'High-revisit optical imaging with automated tipping and monitoring', 'https://www.blacksky.com/'),
 'orbitalsidekick': ('Orbital Sidekick', 'USA', 'eo', 'Hyperspectral monitoring of pipelines, methane and mineralogy', 'https://www.orbitalsidekick.com/'),
 'wyvern':       ('Wyvern', 'Canada', 'eo', 'Deployable-optic hyperspectral imaging for agriculture and forestry', 'https://wyvern.space/'),
 'kuva':         ('Kuva Space', 'Finland', 'eo', 'Hyperspectral cubesat constellation with a data-products business', 'https://kuvaspace.com/'),
 'satvu':        ('SatVu', 'UK', 'eo', 'High-resolution thermal infrared imaging of the built environment', 'https://www.satellitevu.com/'),
 'hydrosat':     ('Hydrosat', 'USA', 'eo', 'Thermal infrared for crop water stress and yield forecasting', 'https://hydrosat.com/'),
 'ororatech':    ('OroraTech', 'Germany', 'eo', 'Thermal cubesats for wildfire detection and global heat monitoring', 'https://ororatech.com/'),
 'hawkeye360':   ('HawkEye 360', 'USA', 'rf', 'Formation-flying RF geolocation: dark ships, GPS interference, emitter mapping', 'https://www.he360.com/'),
 'unseenlabs':   ('Unseenlabs', 'France', 'rf', 'Single-satellite RF maritime domain awareness (BRO constellation)', 'https://unseenlabs.space/'),
 'kleos':        ('Kleos Space', 'Luxembourg', 'rf', 'RF reconnaissance clusters; wound down in 2024 - a cautionary comparison', 'https://en.wikipedia.org/wiki/Kleos_Space'),
 'aurora':       ('Aurora Insight', 'USA', 'rf', 'Spectrum measurement and RF environment mapping from space and air', 'https://www.aurorainsight.com/'),
 'descartes':    ('Descartes Labs', 'USA', 'eo', 'Petabyte-scale geospatial data refinery and analytics platform', 'https://www.descarteslabs.com/'),
 'earthdaily':   ('EarthDaily Analytics', 'Canada', 'eo', 'Analysis-ready imagery pipelines and a daily-change constellation', 'https://earthdaily.com/'),
 'esri':         ('Esri', 'USA', 'eo', 'ArcGIS - the reference GIS software stack for mapping and spatial analysis', 'https://www.esri.com/'),
 'sentinelhub':  ('Sentinel Hub (Planet Insights)', 'Slovenia / USA', 'eo', 'Satellite data APIs and on-the-fly processing for developers', 'https://www.sentinel-hub.com/'),
 'regrow':       ('Regrow Ag', 'USA', 'eo', 'Remote-sensing agronomy: crop practice detection and soil carbon at field scale', 'https://www.regrow.ag/'),
 'gro':          ('Gro Intelligence', 'USA', 'eo', 'Agricultural and climate data models; ceased trading in 2024', 'https://en.wikipedia.org/wiki/Gro_Intelligence'),
 'climateai':    ('ClimateAi', 'USA', 'eo', 'Seasonal climate risk forecasting for agriculture and supply chains', 'https://climate.ai/'),
 'tomorrowio':   ('Tomorrow.io', 'USA', 'eo', 'Owns weather radar/sounder satellites and sells operational forecasts', 'https://www.tomorrow.io/'),
 'climavision':  ('Climavision', 'USA', 'eo', 'Private radar and satellite data fused into high-resolution forecasts', 'https://climavision.com/'),
 'jupiter':      ('Jupiter Intelligence', 'USA', 'eo', 'Physical climate risk analytics for assets and infrastructure', 'https://jupiterintel.com/'),
 'ursa':         ('Ursa Space Systems', 'USA', 'eo', 'Virtual constellation: buys SAR and optical capacity, sells the analysis', 'https://ursaspace.com/'),
 'orbitalinsight': ('Orbital Insight (Privateer)', 'USA', 'eo', 'Geospatial activity analytics from imagery and location data', 'https://www.privateer.com/'),
 'spaceknow':    ('SpaceKnow', 'USA / Czechia', 'eo', 'Economic and defence indices derived from satellite imagery', 'https://www.spaceknow.com/'),
 'planetarycomputer': ('Microsoft Planetary Computer', 'USA', 'eo', 'Open Earth data catalogue with hosted compute and natural-language querying', 'https://planetarycomputer.microsoft.com/'),
 'ubotica':      ('Ubotica', 'Ireland', 'sat', 'Onboard AI inference hardware flown on ESA Phi-Sat and commercial missions', 'https://ubotica.com/'),
 'unibap':       ('Unibap', 'Sweden', 'sat', 'SpaceCloud onboard compute and an app store for in-orbit processing', 'https://unibap.com/'),
 'aethero':      ('Aethero', 'USA', 'sat', 'Radiation-tolerant edge GPUs for autonomous spacecraft', 'https://aethero.com/'),
 'littleplace':  ('Little Place Labs', 'USA', 'sat', 'Near-real-time onboard analytics delivered seconds after capture', 'https://littleplace.com/'),
 'starcloud':    ('Starcloud', 'USA', 'sat', 'Orbital data centres powered by continuous sunlight', 'https://www.starcloud.com/'),
 'rocketlab':    ('Rocket Lab', 'USA / NZ', 'launch', 'Electron small launcher, Neutron in build, plus satellite components', 'https://www.rocketlabusa.com/'),
 'firefly':      ('Firefly Aerospace', 'USA', 'launch', 'Alpha launcher, Blue Ghost lunar lander and orbital transfer vehicles', 'https://fireflyspace.com/'),
 'relativity':   ('Relativity Space', 'USA', 'launch', '3D-printed launch vehicles and engines; Terran R in development', 'https://www.relativityspace.com/'),
 'isar':         ('Isar Aerospace', 'Germany', 'launch', 'Spectrum small launcher built on in-house Aquila engines', 'https://www.isaraerospace.com/'),
 'rfa':          ('Rocket Factory Augsburg', 'Germany', 'launch', 'RFA ONE staged-combustion small launcher aimed at low cost per kilo', 'https://www.rfa.space/'),
 'orbex':        ('Orbex', 'UK', 'launch', 'Prime micro-launcher running on bio-propane, built around 3D-printed engines', 'https://orbex.space/'),
 'skyrora':      ('Skyrora', 'UK', 'launch', 'Suborbital Skylark and the Skyrora XL small launcher', 'https://www.skyrora.com/'),
 'gilmour':      ('Gilmour Space', 'Australia', 'launch', 'Eris hybrid-propulsion small launcher and satellite platforms', 'https://www.gspace.com/'),
 'interstellar': ('Interstellar Technologies', 'Japan', 'launch', 'MOMO sounding rocket and the ZERO small orbital launcher', 'https://www.istellartech.com/en/'),
 'stoke':        ('Stoke Space', 'USA', 'launch', 'Fully and rapidly reusable two-stage vehicle with a novel reusable upper stage', 'https://www.stokespace.com/'),
 'spacex':       ('SpaceX', 'USA', 'launch', 'Falcon 9 reuse economics, Starship, and the Starlink constellation', 'https://www.spacex.com/'),
 'blueorigin':   ('Blue Origin', 'USA', 'launch', 'New Shepard suborbital flights and the New Glenn orbital vehicle', 'https://www.blueorigin.com/'),
 'spaceperspective': ('Space Perspective', 'USA', 'launch', 'Stratospheric balloon capsule flights for passengers', 'https://spaceperspective.com/'),
 'worldview':    ('World View', 'USA', 'launch', 'Stratospheric balloons for remote sensing and crewed edge-of-space flights', 'https://worldview.space/'),
 'varda':        ('Varda Space Industries', 'USA', 'sat', 'In-space pharmaceutical crystallisation with a returning capsule', 'https://www.varda.com/'),
 'spaceforge':   ('Space Forge', 'UK', 'sat', 'Reusable in-orbit manufacturing of semiconductor materials', 'https://www.spaceforge.com/'),
 'explorationco': ('The Exploration Company', 'Germany / France', 'sat', 'Nyx reusable cargo capsule for station resupply and return', 'https://www.exploration.space/'),
 'atmos':        ('ATMOS Space Cargo', 'Germany', 'sat', 'PHOENIX inflatable-heatshield re-entry capsules for payload return', 'https://atmos-space-cargo.com/'),
 'inversion':    ('Inversion Space', 'USA', 'sat', 'Re-entry vehicles that store cargo in orbit and return it on demand', 'https://www.inversionspace.com/'),
 'sierra':       ('Sierra Space', 'USA', 'sat', 'Dream Chaser lifting-body spaceplane and LIFE inflatable habitats', 'https://www.sierraspace.com/'),
 'radian':       ('Radian Aerospace', 'USA', 'launch', 'Single-stage-to-orbit horizontal take-off and landing spaceplane', 'https://www.radianaerospace.com/'),
 'exotrail':     ('Exotrail', 'France', 'launch', 'Electric propulsion plus the spacevan orbital transfer vehicle', 'https://www.exotrail.com/'),
 'thrustme':     ('ThrustMe', 'France', 'launch', 'Iodine electric propulsion for smallsats, flown since 2020', 'https://www.thrustme.fr/'),
 'benchmark':    ('Benchmark Space Systems', 'USA', 'launch', 'Non-toxic chemical and hybrid propulsion with in-space refuelling plans', 'https://www.benchmarkspacesystems.com/'),
 'phasefour':    ('Phase Four', 'USA', 'launch', 'RF thruster using a plasma source with no electrodes or cathodes', 'https://phasefour.io/'),
 'morpheus':     ('Morpheus Space', 'Germany / USA', 'launch', 'Field-emission electric propulsion and constellation-scale mobility software', 'https://www.morpheus-space.com/'),
 'dawn':         ('Dawn Aerospace', 'New Zealand / Netherlands', 'launch', 'Green bipropellant thrusters and the Mk-II Aurora rocket-powered aircraft', 'https://www.dawnaerospace.com/'),
 'orbion':       ('Orbion Space Technology', 'USA', 'launch', 'Mass-manufactured Hall-effect thrusters for smallsat constellations', 'https://orbionspace.com/'),
 'ecaps':        ('Bradford ECAPS', 'Sweden', 'launch', 'LMP-103S high-performance green monopropellant, flight-proven since 2010', 'https://ecaps.space/'),
 'ursamajor':    ('Ursa Major', 'USA', 'launch', 'Rocket engines sold as a product to launch and defence primes', 'https://www.ursamajor.com/'),
 'agile':        ('Agile Space Industries', 'USA', 'launch', 'In-space thrusters and propulsion test services for other builders', 'https://agilespaceindustries.com/'),
 'astroscale':   ('Astroscale', 'Japan', 'ssa', 'Debris removal, life extension and close-approach inspection missions', 'https://astroscale.com/'),
 'clearspace':   ('ClearSpace', 'Switzerland', 'ssa', 'ESA-backed capture and de-orbit of large derelict objects', 'https://clearspace.today/'),
 'orbitfab':     ('Orbit Fab', 'USA', 'launch', 'In-orbit refuelling: standard fuel ports and propellant depots', 'https://www.orbitfab.com/'),
 'starfish':     ('Starfish Space', 'USA', 'ssa', 'Otter servicing vehicle using electric propulsion and autonomous docking', 'https://www.starfishspace.com/'),
 'spacelogistics': ('Northrop Grumman SpaceLogistics', 'USA', 'ssa', 'Mission Extension Vehicles that docked with and flew ageing Intelsat craft', 'https://www.northropgrumman.com/space/space-logistics-services'),
 'dorbit':       ('D-Orbit', 'Italy', 'sat', 'ION orbital transfer vehicle, last-mile delivery and in-orbit services', 'https://www.dorbit.space/'),
 'kallmorris':   ('Kall Morris Inc', 'USA', 'ssa', 'Captures tumbling debris without grapple fixtures, using adhesive end effectors', 'https://www.kallmorris.com/'),
 'leolabs':      ('LeoLabs', 'USA', 'ssa', 'Global phased-array radar network tracking LEO objects commercially', 'https://leolabs.space/'),
 'slingshot':    ('Slingshot Aerospace', 'USA', 'ssa', 'Space traffic coordination, optical sensor network and threat analytics', 'https://www.slingshot.space/'),
 'exoanalytic':  ('ExoAnalytic Solutions', 'USA', 'ssa', 'Worldwide optical telescope network watching GEO behaviour', 'https://exoanalytic.com/'),
 'northstar':    ('NorthStar Earth & Space', 'Canada', 'ssa', 'Space-based optical SSA - watching space from space rather than the ground', 'https://northstar-data.com/'),
 'vyoma':        ('Vyoma', 'Germany', 'ssa', 'In-orbit surveillance satellites and collision-avoidance services', 'https://www.vyoma.space/'),
 'kayhan':       ('Kayhan Space', 'USA', 'ssa', 'Automated conjunction screening and manoeuvre planning (Pathfinder)', 'https://kayhan.space/'),
 'sharemyspace': ('Share My Space', 'France', 'ssa', 'Optical debris tracking and a catalogue aimed at European autonomy', 'https://www.sharemyspace.space/'),
 'terranorbital': ('Terran Orbital (Lockheed Martin)', 'USA', 'sat', 'Smallsat buses at constellation volume, including Tranche satellites', 'https://terranorbital.com/'),
 'nanoavionics': ('NanoAvionics (Kongsberg)', 'Lithuania', 'sat', 'Preconfigured nanosat and microsat buses sold as a product line', 'https://nanoavionics.com/'),
 'aacclyde':     ('AAC Clyde Space', 'Sweden / UK', 'sat', 'Cubesat subsystems, full missions and space-data-as-a-service', 'https://www.aac-clyde.space/'),
 'bluecanyon':   ('Blue Canyon Technologies (RTX)', 'USA', 'sat', 'XB-series buses and the XACT attitude determination and control units', 'https://bluecanyontech.com/'),
 'gomspace':     ('GomSpace', 'Denmark', 'sat', 'Nanosatellite platforms, radios and mission services', 'https://gomspace.com/'),
 'opencosmos':   ('Open Cosmos', 'UK', 'sat', 'Mission-as-a-service: satellite, launch, ground and data in one contract', 'https://www.open-cosmos.com/'),
 'apex':         ('Apex Space', 'USA', 'sat', 'Productised satellite buses built on an assembly line for fast delivery', 'https://www.apexspace.com/'),
 'satrec':       ('Satrec Initiative', 'South Korea', 'sat', 'High-resolution EO satellites and payloads exported to national customers', 'https://www.satreci.com/'),
 'endurosat':    ('EnduroSat', 'Bulgaria', 'sat', 'Modular cubesat components and shared-satellite missions', 'https://www.endurosat.com/'),
 'exolaunch':    ('Exolaunch', 'Germany', 'sat', 'Deployment systems and rideshare integration for smallsats', 'https://exolaunch.com/'),
 'oxfordspace':  ('Oxford Space Systems', 'UK', 'sat', 'Deployable antennas and booms that stow small and unfurl precisely', 'https://oxford.space/'),
 'redwire':      ('Redwire Space', 'USA', 'sat', 'Deployable structures, solar arrays, in-space manufacturing and avionics', 'https://redwirespace.com/'),
 'beyondgravity': ('Beyond Gravity (RUAG Space)', 'Switzerland', 'heavy', 'Launcher fairings, structures, mechanisms and satellite electronics', 'https://www.beyondgravity.com/'),
 'cubespace':    ('CubeSpace', 'South Africa', 'sat', 'Plug-and-play attitude determination and control for cubesats', 'https://www.cubespace.co.za/'),
 'anello':       ('Anello Photonics', 'USA', 'rf', 'Silicon photonic optical gyroscope on a chip for navigation without GNSS', 'https://www.anellophotonics.com/'),
 'kvh':          ('KVH Industries', 'USA', 'rf', 'Fibre-optic gyros and inertial systems for guidance and stabilisation', 'https://www.kvh.com/'),
 'safran':       ('Safran Electronics & Defense', 'France', 'rf', 'Inertial navigation, optronics and avionics for aerospace and defence', 'https://www.safran-group.com/'),
 'honeywell':    ('Honeywell Aerospace', 'USA', 'rf', 'Avionics, inertial sensors and spacecraft electronics at prime scale', 'https://aerospace.honeywell.com/'),
 'teledyne':     ('Teledyne e2v', 'UK / USA', 'rf', 'Space-qualified imaging sensors, processors and radiation-tolerant parts', 'https://www.teledyneimaging.com/'),
 'mercury':      ('Mercury Systems', 'USA', 'rf', 'Rugged processing, RF subsystems and secure electronics for defence', 'https://www.mrcy.com/'),
 'thalesalenia': ('Thales Alenia Space', 'France / Italy', 'sat', 'Full-stack satellite prime: payloads, platforms, integration and ground', 'https://www.thalesaleniaspace.com/'),
 'viasat':       ('Viasat', 'USA', 'rf', 'High-throughput satellite broadband, terminals and government comms', 'https://www.viasat.com/'),
 'kymeta':       ('Kymeta', 'USA', 'rf', 'Flat-panel electronically steered antennas for on-the-move connectivity', 'https://www.kymetacorp.com/'),
 'isotropic':    ('All.Space (Isotropic Systems)', 'UK', 'rf', 'Multi-beam optical-RF terminals linking several satellites at once', 'https://all.space/'),
 'astspacemobile': ('AST SpaceMobile', 'USA', 'rf', 'Direct-to-handset broadband from very large unfolding phased arrays', 'https://ast-science.com/'),
 'lynk':         ('Lynk Global', 'USA', 'rf', 'Satellite-direct-to-standard-phone messaging service', 'https://lynk.world/'),
 'skylo':        ('Skylo', 'USA / India', 'rf', 'Non-terrestrial network service over existing GEO satellites and 3GPP NTN', 'https://www.skylo.tech/'),
 'omnispace':    ('Omnispace', 'USA', 'rf', 'Global 5G NTN using S-band spectrum and a hybrid LEO-GEO architecture', 'https://omnispace.com/'),
 'keplercomms':  ('Kepler Communications', 'Canada', 'rf', 'Optical data relay network in LEO - note the name clash with India\u2019s Kepler Aerospace', 'https://kepler.space/'),
 'myriota':      ('Myriota', 'Australia', 'rf', 'Low-power satellite IoT for remote assets with years of battery life', 'https://myriota.com/'),
 'astrocast':    ('Astrocast', 'Switzerland', 'rf', 'L-band nanosatellite IoT network and modules', 'https://www.astrocast.com/'),
 'xona':         ('Xona Space Systems', 'USA', 'rf', 'Pulsar LEO PNT constellation: stronger, encrypted alternative to GNSS', 'https://www.xonaspace.com/'),
 'trustpoint':   ('TrustPoint', 'USA', 'rf', 'Commercial LEO PNT designed for jam-resistant precise positioning', 'https://www.trustpointgps.com/'),
 'satelles':     ('Satelles (Iridium STL)', 'USA', 'rf', 'Timing and positioning delivered over the Iridium constellation', 'https://www.iridium.com/services/satelles-stl/'),
 'septentrio':   ('Septentrio', 'Belgium', 'rf', 'High-precision multi-constellation GNSS receivers with interference resilience', 'https://www.septentrio.com/'),
 'ublox':        ('u-blox', 'Switzerland', 'rf', 'GNSS modules and chips for mass-market positioning', 'https://www.u-blox.com/'),
 'trimble':      ('Trimble', 'USA', 'rf', 'Precise positioning hardware and correction services for field industries', 'https://www.trimble.com/'),
 'what3words':   ('what3words', 'UK', 'eo', 'Three-word addressing grid for places without street addresses', 'https://what3words.com/'),
 'ksat':         ('Kongsberg Satellite Services (KSAT)', 'Norway', 'sat', 'The largest commercial ground-station network, polar to equatorial', 'https://www.ksat.no/'),
 'leafspace':    ('Leaf Space', 'Italy', 'sat', 'Ground-segment-as-a-service for smallsat operators', 'https://leaf.space/'),
 'awsgs':        ('AWS Ground Station', 'USA', 'sat', 'Antennas rented by the minute, with downlinked data landing straight in the cloud', 'https://aws.amazon.com/ground-station/'),
 'atlasspace':   ('ATLAS Space Operations', 'USA', 'sat', 'Freedom software platform federating third-party antennas', 'https://atlasground.com/'),
 'ansys':        ('Ansys (STK / Systems Tool Kit)', 'USA', 'heavy', 'Physics simulation and the mission-analysis standard for orbital modelling', 'https://www.ansys.com/'),
 'dassault':     ('Dassault Syst\u00e8mes', 'France', 'heavy', '3DEXPERIENCE: CAD, simulation and digital-twin engineering platforms', 'https://www.3ds.com/'),
 'gmv':          ('GMV', 'Spain', 'heavy', 'Flight dynamics, mission control and GNSS software behind many missions', 'https://www.gmv.com/'),
 'sener':        ('SENER Aeroespacial', 'Spain', 'heavy', 'Precision mechanisms, pointing systems and structures for space primes', 'https://www.aeroespacial.sener/'),
 'aerojet':      ('L3Harris Aerojet Rocketdyne', 'USA', 'heavy', 'Rocket engines and propulsion hardware for launchers and defence', 'https://www.rocket.com/'),
 'capgemini':    ('Capgemini Engineering', 'France', 'heavy', 'Outsourced R&D and engineering services across aerospace programmes', 'https://capgemini-engineering.com/'),
 'element':      ('Element Materials Technology', 'UK', 'heavy', 'Independent testing, qualification and certification for aerospace parts', 'https://www.element.com/'),
 'gallagher':    ('Gallagher Space', 'UK / USA', 'heavy', 'Specialist space insurance broking for launch and in-orbit risk', 'https://www.ajg.com/'),
 'marsh':        ('Marsh Space Projects', 'UK', 'heavy', 'Space risk placement and structured cover for operators and lenders', 'https://www.marsh.com/'),
 'axaxl':        ('AXA XL Space', 'France / USA', 'heavy', 'Underwriter of launch and in-orbit policies, and of newer parametric covers', 'https://axaxl.com/'),
 'amsat':        ('AMSAT', 'International', 'sat', 'Volunteer-built amateur radio satellites - the original student pipeline', 'https://www.amsat.org/'),
 'librespace':   ('Libre Space Foundation', 'Greece', 'sat', 'Open-source satellites, ground stations (SatNOGS) and launcher work', 'https://libre.space/'),
 'albedo':       ('Albedo', 'USA', 'eo', 'Very-low-Earth-orbit satellites for 10 cm optical and thermal imagery', 'https://albedo.com/'),
}

# Indian company number -> list of global ids
M = {
 '01': ['regrow', 'esri', 'descartes'],
 '02': ['relativity', 'rocketlab', 'orbex'],
 '03': ['thalesalenia', 'redwire', 'beyondgravity'],
 '04': ['beyondgravity', 'thalesalenia'],
 '05': ['teledyne', 'mercury', 'septentrio'],
 '06': ['viasat', 'spacex', 'kymeta'],
 '07': ['ksat', 'viasat', 'thalesalenia'],
 '08': ['beyondgravity', 'redwire', 'sener'],
 '09': ['satrec', 'terranorbital', 'satellogic'],
 '10': ['exotrail', 'thrustme', 'phasefour', 'morpheus', 'albedo'],
 '11': ['teledyne', 'mercury', 'honeywell'],
 '12': ['teledyne', 'mercury'],
 '13': ['nanoavionics', 'terranorbital', 'exolaunch', 'ksat', 'opencosmos'],
 '14': ['leolabs', 'slingshot', 'exoanalytic', 'northstar', 'vyoma'],
 '15': ['iceye', 'umbra', 'planet'],
 '16': ['thalesalenia', 'mercury'],
 '17': ['astroscale', 'orbitfab', 'starfish', 'spacelogistics'],
 '18': ['descartes', 'sentinelhub', 'planet'],
 '19': ['hawkeye360', 'aurora', 'keplercomms'],
 '20': ['sener', 'aerojet', 'beyondgravity'],
 '21': ['benchmark', 'dawn', 'ecaps', 'kayhan'],
 '22': ['capgemini', 'element'],
 '23': ['sener', 'aerojet'],
 '24': ['what3words'],
 '25': ['orbitalsidekick', 'wyvern', 'kuva', 'planet'],
 '26': ['planet', 'blacksky', 'maxar', 'earthdaily'],
 '27': ['esri', 'sentinelhub'],
 '28': ['rocketlab', 'firefly', 'isar', 'gilmour'],
 '29': ['amsat', 'librespace'],
 '30': ['gmv', 'opencosmos'],
 '31': ['thalesalenia', 'redwire', 'beyondgravity'],
 '32': ['orbitalinsight', 'spaceknow', 'descartes'],
 '33': ['opencosmos', 'leafspace'],
 '34': ['sener', 'aerojet'],
 '35': ['hawkeye360', 'unseenlabs', 'kleos'],
 '36': ['ansys', 'dassault'],
 '37': ['regrow', 'gro'],
 '38': ['teledyne', 'mercury'],
 '39': ['oxfordspace', 'redwire', 'sierra'],
 '40': ['sierra', 'explorationco', 'atmos', 'inversion', 'radian'],
 '41': ['planetarycomputer', 'descartes', 'ansys'],
 '42': ['cubespace', 'bluecanyon'],
 '43': ['rfa', 'isar', 'orbex'],
 '44': ['librespace', 'amsat'],
 '45': ['orbitalinsight', 'descartes'],
 '46': ['anello', 'kvh', 'safran', 'honeywell'],
 '47': ['opencosmos', 'gmv'],
 '48': ['thalesalenia', 'kymeta'],
 '49': ['ursamajor', 'dawn', 'agile'],
 '50': ['astroscale', 'clearspace', 'kallmorris', 'sharemyspace'],
 '51': ['gomspace', 'endurosat'],
 '52': ['descartes', 'planetarycomputer'],
 '53': ['kayhan', 'slingshot', 'ansys'],
 '54': ['oxfordspace', 'exolaunch', 'redwire'],
 '55': ['ecaps', 'dawn', 'benchmark'],
 '56': ['esri', 'sentinelhub'],
 '57': ['septentrio', 'ublox', 'xona'],
 '58': ['stoke', 'spacex', 'relativity'],
 '59': ['esri', 'sentinelhub'],
 '60': ['endurosat', 'bluecanyon', 'beyondgravity'],
 '61': ['sentinelhub', 'planetarycomputer', 'esri'],
 '62': ['apex', 'nanoavionics'],
 '63': ['aacclyde', 'endurosat', 'nanoavionics'],
 '64': ['aethero', 'hawkeye360'],
 '65': ['varda', 'spaceforge', 'explorationco'],
 '66': ['esri', 'maxar'],
 '67': ['capgemini', 'ansys'],
 '68': ['gallagher', 'marsh', 'axaxl'],
 '69': ['tomorrowio', 'climavision', 'climateai'],
 '70': ['ublox', 'trimble', 'satelles'],
 '71': ['exotrail', 'dorbit', 'albedo'],
 '72': ['iceye', 'capella', 'umbra'],
 '73': ['gmv', 'ansys', 'littleplace'],
 '74': ['aethero', 'mercury', 'teledyne'],
 '75': ['regrow', 'gro'],
 '76': ['element', 'beyondgravity'],
 '77': ['honeywell', 'thalesalenia'],
 '78': ['astspacemobile', 'lynk', 'xona'],
 '79': ['satvu', 'hydrosat', 'ororatech'],
 '80': ['maxar', 'earthdaily'],
 '81': ['regrow', 'gro', 'climateai'],
 '82': ['varda', 'spaceforge'],
 '83': ['sener', 'element'],
 '84': ['iceye', 'synspective', 'iqps'],
 '85': ['ubotica', 'littleplace', 'awsgs'],
 '86': ['stoke', 'radian', 'interstellar'],
 '87': ['spaceperspective', 'worldview', 'blueorigin'],
 '88': ['slingshot', 'keplercomms', 'kayhan'],
 '89': ['skyrora', 'interstellar', 'blueorigin'],
 '90': ['ursa', 'blacksky', 'earthdaily'],
 '91': ['kymeta', 'isotropic'],
 '92': ['starcloud'],
 '93': ['ursa', 'orbitalinsight'],
 '94': ['ursamajor', 'ecaps', 'agile'],
 '95': ['ursamajor', 'agile'],
 '96': ['skylo', 'omnispace', 'astspacemobile'],
 '97': ['hawkeye360', 'unseenlabs'],
 '98': ['climateai', 'jupiter', 'tomorrowio'],
 '99': ['earthdaily', 'ursa'],
 '100': ['ubotica', 'aethero', 'unibap'],
 '101': ['explorationco', 'spacex', 'sierra'],
 '102': ['xona', 'trustpoint', 'satelles'],
 '103': ['regrow', 'climateai'],
 '104': ['apex', 'bluecanyon', 'terranorbital'],
 '105': ['myriota', 'astrocast', 'skylo'],
}

# Pairs worth a sentence of their own.
NOTES = {
 ('02', 'relativity'): 'Both print their engines whole: Agnikul\u2019s Agnilet and Relativity\u2019s Aeon are single-piece 3D-printed designs.',
 ('19', 'keplercomms'): 'Same name, different businesses - Canada\u2019s Kepler Communications builds an optical relay network, India\u2019s Kepler Aerospace does RF intelligence.',
 ('35', 'kleos'): 'Kleos chased the same RF-geolocation market and wound down in 2024; a reminder that the business model, not the physics, is the hard part.',
 ('92', 'starcloud'): 'Both are betting that compute in orbit beats downlinking the data - Starcloud on sunlight-powered data centres, TM2 on orbital data centres from India.',
 ('46', 'anello'): 'The closest match on this page: a photonic gyroscope reduced to a chip, replacing spinning or fibre-optic inertial units.',
 ('24', 'what3words'): 'Both replace street addresses with a short, speakable code so that deliveries and emergency services can find a doorstep.',
 ('15', 'iceye'): 'GalaxEye goes further than ICEYE\u2019s single sensor by fusing SAR with optical on one satellite.',
 ('21', 'ecaps'): 'The green-propellant comparison: ECAPS\u2019 LMP-103S has flown since 2010, Manastu\u2019s hydrogen-peroxide blend is the Indian attempt at the same substitution for hydrazine.',
 ('29', 'amsat'): 'Both put non-professionals in orbit - AMSAT through amateur radio clubs, Space Kidz through school and college teams.',
 ('68', 'gallagher'): 'Space risk as a financial product rather than a technical one: broking and placing launch and in-orbit cover.',
 ('14', 'leolabs'): 'LeoLabs watches LEO from the ground with phased-array radar; Digantara is building the same picture from orbit.',
 ('50', 'astroscale'): 'Active debris removal as a commercial service - Astroscale has flown demonstrations, Cosmoserve is at design stage.',
 ('87', 'spaceperspective'): 'Both sell the view rather than the altitude: a slow pressurised capsule ride instead of a rocket.',
 ('65', 'varda'): 'Manufacturing in orbit and bringing the product home - Varda returns pharmaceutical crystals, Inbound is building the lifting-body vehicle to do the same.',
 ('58', 'stoke'): 'Both are aiming straight at full reusability, including the upper stage, rather than reusing the booster alone.',
}

ind = {c['num']: c for c in json.load(io.open(REPO + r'\data\indi-space.json', encoding='utf-8'))}
links = []
for num, gids in M.items():
    if num not in ind:
        raise SystemExit('unknown Indian company ' + num)
    for g in gids:
        if g not in G:
            raise SystemExit('unknown global company ' + g)
        links.append({'i': num, 'g': g, 'note': NOTES.get((num, g), '')})

out = {
    'compiled': '2 October 2026',
    'about': ('Global reference companies set against the Indian firms on the Indi-Space page that do comparable work. '
              'A pairing means the two are solving a similar problem - not that they are at the same stage, scale or maturity.'),
    'global': [{'id': k, 'name': v[0], 'country': v[1], 'cat': v[2], 'focus': v[3], 'url': v[4]} for k, v in sorted(G.items(), key=lambda x: x[1][0].lower())],
    'links': links,
}
io.open(REPO + r'\data\analogues.json', 'w', encoding='utf-8').write(json.dumps(out, ensure_ascii=False, indent=1))
print('global companies:', len(G), '| Indian companies mapped:', len(M), '| links:', len(links))
unmapped = [n for n in ind if n not in M]
print('Indian companies with no analogue yet:', unmapped)
